sudo: required
dist: xenial
matrix:
        include:
              - language: python
                virtualenv:
                  system_site_packages: true
                python:
                - '3.5'
                install:
                - pip3 install numpy 
                - python3 setup.py build
                - python3 setup.py install
                script:
                - python3 examples/random-vectors.py
              - language: cpp
                install:
                - sudo apt-get install -y python3-pip python3-setuptools
                - mkdir bin && cd bin
                - cmake .. && make
                script:
                - ./Test


